---
title: "The influence of temperature and vapour pressure deficit on conidia germination and germ tubes production in an Australian Podosphaera xanthii isolate."
description: |
  Data analysis for paper
author:
  - name: Paul Melloy 
    url: https://twitter.com/PaulMelloy
    affiliation: The University of Queensland
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r libraries,message = FALSE}
library(readxl)
library(dplyr)
library(data.table)
if("epiphytoolR" %in% names(installed.packages()[, "Package"]) == FALSE) {
  remotes::install_github(repo = "https://github.com/PaulMelloy/epiphytoolR",
                          ref = "dev",
                          upgrade = "never"
                          )
}
```

```{r import_data, message = FALSE}
germ_tm <- read_xlsx("data/Chapter 5 (germination vs temperature vs time incubation at low VPD).xlsx",
                      range = "A1:N32")

g_time_vpd <- bind_rows(
  read_xls(
    "data/chapter 5 (germination vs VPD vs temp vs RH).xls",
    sheet = "Sheet1",
    range = "B63:F158",
    col_names = c("RH", "Tm", "i_period", "rep", "germ_n")
  ),
  read_xls(
    "data/chapter 5 (germination vs VPD vs temp vs RH).xls",
    sheet = "Sheet1",
    range = "I63:M158",
    col_names = c("RH", "Tm", "i_period", "rep", "germ_n")
  ),
  read_xls(
    "data/chapter 5 (germination vs VPD vs temp vs RH).xls",
    sheet = "Sheet1",
    range = "P63:T158",
    col_names = c("RH", "Tm", "i_period", "rep", "germ_n")
  )
)

branch_vpd <- 
  read_xls("data/Chapter 5 (germination vs VPD vs temp vs RH).xls",
           sheet = "Sheet2",
           range = "AF3:AI182",
           col_names = c("vpd", "germ_tubes", "rep", "n"))


germ_vpd_tm <- 
  fread("data/220308_branching_vpd_temperature.csv",nrows = 29,header = TRUE)
           

```

## Temperature effect on germination experiment
This data investigated the effect of
```{r clean_germ_tm}
# Remove unnecessary columns and rows
germ_tm <- data.table(germ_tm)[-c(1,2,7:10,15:18,23:27),-c(4,6,7,9,11,13)]

# rename leaf number column
setnames(germ_tm,
         old = c("Temperature" ,"...2"),
         new = c("i_period","leaf"))

# fill incubation period
germ_tm[13:16,i_period := "48h"]
# remove "h" and make column numeric
germ_tm[,i_period := as.numeric(gsub("h","",germ_tm$i_period))]

# fill in na's with previous non NA value
setnafill(germ_tm,
          type = "locf",
          cols = "i_period")

# reshape data to long format
germ_tm <- 
   melt(germ_tm,
     id.vars = c("i_period","leaf"),
     measure.vars = c("17oC", "19oC", "22oC", "25oC", "28oC", "31oC"),
     variable.name = "Tm",
     value.name = "germ_conidia")

# remove "oC" from temperature and make it numeric
germ_tm[, c("Tm","germ_conidia","non_germ_conidia") := list(as.numeric(gsub("oC","",Tm)),
                                            as.numeric(germ_conidia),
                                            100 - as.numeric(germ_conidia))]

# Change column order
setcolorder(germ_tm,
            neworder = c("Tm", "i_period", "leaf", "germ_conidia","non_germ_conidia"))

# save data into cache
fwrite(x = germ_tm,
       file = "cache/germination_temperature.csv")

```

## Experimental data on VPD effect on germination

```{r clean_g_time_vpd}
# remove characters from temperature and time, make RH as a percentage
setDT(g_time_vpd)[, c("RH", "Tm", "i_period","non_germ_n") :=
                  list(RH * 100,
                       as.numeric(gsub("C", "", Tm)),
                       as.numeric(gsub("h", "", i_period)),
                       100 - germ_n)]

# add vpd column
g_time_vpd[, vpd := round(epiphytoolR::calc_vpd(RH = RH,
                                              Tm = Tm), 
                        3)]

# Change column order
setcolorder(g_time_vpd,
            neworder = c("RH", "Tm", "vpd", "i_period", "rep", "germ_n", "non_germ_n"))

# write out clean data
fwrite(g_time_vpd,
       file = "cache/germination_response_to_vpd.csv")
```


## VPD effect on germination and branching
This data investigated the effect of
```{r clean_germ_tm}
# make data.table format and add temperature and humidity
branch_vpd <- data.table(branch_vpd)[, c("Tm","RH") := list(rep(c(22,25,28), each = 12, times = 5),
                                                            rep(c(95,85,75,55,32), each = 12*3))]

# recalculate vpd
branch_vpd[, vpd := round(epiphytoolR::calc_vpd(RH = RH,
                                                Tm = Tm),
                          3)]

# remove "b" from germ_tubes and make it numeric
branch_vpd[, germ_tubes := as.numeric(gsub("b","",germ_tubes))]

# add column for non-germinated spores
branch_vpd[, c("germ_tubes", "n", "non_germ") := list(germ_tubes, n, 100 - sum(n)), by = list(vpd, Tm, RH, rep)]

# Change column order
setcolorder(branch_vpd,
            neworder = c("vpd", "Tm", "RH","rep","germ_tubes","n"))

# save data into cache
fwrite(x = branch_vpd,
       file = "cache/branching_vpd.csv")

```

# Effect of vpd at different VPD

```{r clean_germ_tm}
# Remove unnecessary columns and rows
germ_vpd_tm <- germ_vpd_tm[-c(5:10,15:24),-c(1,2,9:12,19:22,29)][-c(13)]

# rename leaf number column
setnames(germ_vpd_tm,
         old = 1:18,
         new = c("0.03_b1","0.13_b1","0.4_b1","0.7_b1","1.2_b1","1.8_b1",
                 "0.03_b2","0.13_b2","0.4_b2","0.7_b2","1.2_b2","1.8_b2",
                 "0.03_b3","0.13_b3","0.4_b3","0.7_b3","1.2_b3","1.8_b3"))

# Add temperature treatment
germ_vpd_tm[ , Tm := rep(c(22,25,28), each = 4)]

# reshape data to long format
germ_vpd_tm <- 
   melt(germ_vpd_tm,
     id.vars = c("Tm"),
     value.name = "conidia",
     variable.factor = FALSE)

# split variable column into two columns vpd and branches and remove variable column
germ_vpd_tm[, c("vpd","branches") := tstrsplit(variable, "_b")][, variable := NULL]

# Change column order
setcolorder(germ_vpd_tm,
            neworder = c("Tm", "vpd", "branches","conidia"))

# set correct classes and add non-germinated
germ_vpd_tm[, c("vpd", 
                "branches", 
                "conidia", 
                "rep") := 
              list(as.numeric(vpd),
                   as.numeric(branches),
                   as.numeric(conidia),
                   rep(1:4,.N/4))]

# obtain vector of non-germinated???????????

# save data into cache
fwrite(x = germ_vpd_tm,
       file = "cache/branching_temperature&VPD.csv")

```



```{r}
# read in data from sas file
dat <- readLines("data/vpd germtube.sas")[3:236]
# cut out non-data lines
dat <- dat[-c(2,55:58,111:114,167:170,223:226)]
#write it to csv
write(dat, "cache/vpd_branches.csv")

# read in data using fread
branch_vpd2 <- fread("cache/vpd_branches.csv")

# Add relative humidity and temperature data
branch_vpd2[ , c("RH","Tm") := list(rep(c(99,95,85,75,50,33),each = 36),
                                    rep(c(22,25,28),each = 12, times = 6))]

# recalculate vpd and convert branches to numeric
branch_vpd2[, c("vpd",
                "bran") :=
              list(round(epiphytoolR::calc_vpd(RH = RH,
                                               Tm = Tm),
                         3),
                   as.numeric(gsub("b", "", bran)))]

# rearrange columns
setcolorder(branch_vpd2,
            neworder = c("Obs", "RH", "Tm", "vpd", "bran", "rep", "numb")
            )

setnames(branch_vpd2,
         old = c("bran", "numb"),
         new = c("branches","conidia"))

branch_vpd2[, non_germ := 100 - sum(conidia), by = .(RH, Tm, vpd, rep)]

fwrite(branch_vpd2,
       file = "cache/branching_under_vpd&Tm.csv")

```











