---
title: "The influence of temperature and vapour pressure deficit on conidia germination and germ tubes production in an Australian Podosphaera xanthii isolate."
description: |
  Data analysis for paper
author:
  - name: Paul Melloy 
    url: https://example.com/norajones
    affiliation: The University of Queensland
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r libraries,message = FALSE}
library(mgcv)
library(lme4)
library(readxl)
library(dplyr)
library(data.table)
remotes::install_github(repo = "https://github.com/PaulMelloy/epiphytoolR",ref = "dev",
                        upgrade = "never" # this should be removed before publishing
                        )
```

```{r import_data, message = FALSE}
germ_tm <- read_xlsx("data/Chapter 5 (germination vs temperature vs time incubation at low VPD).xlsx",
                      range = "A1:N32")

germ_vpd <- bind_rows(
  read_xls(
    "data/chapter 5 (germination vs VPD vs temp vs RH).xls",
    sheet = "Sheet1",
    range = "B63:F158",
    col_names = c("RH", "Tm", "i_period", "rep", "germ_n")
  ),
  read_xls(
    "data/chapter 5 (germination vs VPD vs temp vs RH).xls",
    sheet = "Sheet1",
    range = "I63:M158",
    col_names = c("RH", "Tm", "i_period", "rep", "germ_n")
  ),
  read_xls(
    "data/chapter 5 (germination vs VPD vs temp vs RH).xls",
    sheet = "Sheet1",
    range = "P63:T158",
    col_names = c("RH", "Tm", "i_period", "rep", "germ_n")
  )
)

```

## Temperature effect on germination experiment
This data investigated the effect of
```{r clean_germ_tm}
# Remove unnecessary columns and rows
germ_tm <- data.table(germ_tm)[-c(1,2,7:10,15:18,23:27),-c(4,6,7,9,11,13)]

# rename leaf number column
setnames(germ_tm,
         old = c("Temperature" ,"...2"),
         new = c("i_period","leaf"))

# fill incubation period
germ_tm[13:16,i_period := "48h"]
# remove "h" and make column numeric
germ_tm[,i_period := as.numeric(gsub("h","",germ_tm$i_period))]

# fill in na's with previous non NA value
setnafill(germ_tm,
          type = "locf",
          cols = "i_period")

# reshape data to long format
germ_tm <- 
   melt(germ_tm,
     id.vars = c("i_period","leaf"),
     measure.vars = c("17oC", "19oC", "22oC", "25oC", "28oC", "31oC"),
     variable.name = "Tm",
     value.name = "germ_conidia")

# remove "oC" from temperature and make it numeric
germ_tm[, Tm := as.numeric(gsub("oC","",Tm))]

# Change column order
setcolorder(germ_tm,
            neworder = c("Tm", "i_period", "leaf", "germ_conidia"))

#save data into cache
fwrite(x = germ_tm,
       file = "cache/germination_temperature.csv")

```

## Experimental data on VPD effect on germination

```{r clean_germ_vpd}
# remove characters from temperature and time, make RH as a percentage
setDT(germ_vpd)[, c("RH", "Tm", "i_period") :=
                  list(RH * 100,
                       as.numeric(gsub("C", "", Tm)),
                       as.numeric(gsub("h", "", i_period)))]

# add vpd column
germ_vpd[, vpd := round(epiphytoolR::calc_vpd(RH = RH,
                                              Tm = Tm), 
                        3)]

# Change column order
setcolorder(germ_vpd,
            neworder = c("RH", "Tm", "vpd", "i_period", "rep", "germ_n"))

# write out clean data
fwrite(germ_vpd,
       file = "cache/germination_response_to_vpd.csv")
```




















